Repository kubernetes/klog, pull requests merged in 2018-11, with the labels that each got.

#11 Removed doubled wording from README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#13 glog wrapper that redirects to klog
  glog/README.md
  glog/glog.go
  glog/glog_test.go
Labels: cncf-cla: yes, size/L

#14 Oops! missed a couple of spots for imports
  examples/coexist_glog/coexist_glog.go
  examples/log_file/usage_log_file.go
  examples/set_output/usage_set_output.go
Labels: cncf-cla: yes, lgtm, size/XS

#16 Add a short HOWTO
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#21 Add go_import_path option to .travis.yml
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#17 Add common PR/Issues templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, cncf-cla: yes, lgtm, size/M
