Repository kubernetes/klog, pull requests merged in 2018-12, with the labels that each got.

#27 Update example/readme when using klog and glog
  README.md
  examples/coexist_glog/coexist_glog.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#29 Adds link to k8s/community logging conventions
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#32 Clearify that loglevel is expressed with integers
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#31 stderrthreshold is useless if logtostderr is set
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#33 Add the code of conduct
  CONTRIBUTING.md
  README.md
  code-of-conduct.md
Labels: approved, cncf-cla: yes, lgtm, size/S
