Repository kubernetes/klog, pull requests merged in 2019-09, with the labels that each got.

#92 parse int32s with matching bit size
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#97 Revert "Merge pull request #20 from munnerz/logr"
  klog.go
  klog_test.go
  klogr/klogr.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#91 Starting v2 release following API break
  .travis.yml
  README.md
  examples/coexist_glog/coexist_glog.go
  examples/klogr/main.go
  examples/log_file/usage_log_file.go
  examples/set_output/usage_set_output.go
  go.mod
  integration_tests/internal/main.go
  klog_test.go
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#98 Revert "Revert "Merge pull request #20 from munnerz/logr""
  klog.go
  klog_test.go
  klogr/klogr.go
Labels: approved, cncf-cla: yes, lgtm, size/L
