Repository kubernetes/klog, pull requests merged in 2019-06, with the labels that each got.

#69 Revert "Fix the log duplication issue for --log-file."
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#71 Code Hygiene - glog to klog
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#73 correct documentation
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
