Repository kubernetes/klog, pull requests merged in 2019-07, with the labels that each got.

#74 Add flag to include file's dir in logs
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#75 Add go modules files
  go.mod
  go.sum
Labels: approved, cncf-cla: yes, do-not-merge/hold, lgtm, size/XS

#77 fix broken links
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
