Repository kubernetes/klog, pull requests merged in 2019-08, with the labels that each got.

#80 Backfill integration tests for selecting log destinations
  integration_tests/internal/main.go
  integration_tests/klog_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/important-longterm, size/L

#82 Test with golang 1.12.x
  .travis.yml
Labels: approved, cncf-cla: yes, lgtm, size/XS

#83 Prevent data race in SetOutput* methods
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#78 Fix the log duplication issue for --log-file
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#88 Remove "level" from klogr Info
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#90 Initialize defaults in init
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#20 Add SetLogger function to intercept klog output with logr
  klog.go
  klog_test.go
  klogr/klogr.go
Labels: approved, cncf-cla: yes, lgtm, size/L
