Repository kubernetes/klog, pull requests merged in 2019-02, with the labels that each got.

#41 Adding consistency to OWNERS files
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/XS

#42 Use info in default stderrThreshold
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#45 Bootstrapping a team to take care of klog
  OWNERS
Labels: approved, cncf-cla: yes, lgtm, size/S

#46 go-logr link missing protocol
  klogr/README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#47 klogr: Fix handling of duplicate key/values & add unit tests
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L
