Repository kubernetes/klog, pull requests merged in 2019-03, with the labels that each got.

#49 Open existing log files with O_APPEND at startup
  klog.go
  klog_file.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#50 Revert default changes
  klog.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/critical-urgent, size/S

#48 feat(README): add why klog
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/S

#51 Update embargo doc link in SECURITY_CONTACTS and change PST to PSC
  SECURITY_CONTACTS
Labels: approved, cncf-cla: yes, lgtm, size/XS
