Repository kubernetes/klog, pull requests merged in 2020-04, with the labels that each got.

#126 add structured logs function InfoS and ErrorS fix #125
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#112 Enhanced description for an add_dir_header flag
  klog.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#115 Fix Set method of traceLocation
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#120 "fix a invalid url"
  CONTRIBUTING.md
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, priority/backlog, size/XS

#113 Modify setVState method to use receiver identifier
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#131 Add github actions
  .github/workflows/test.yml
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#135 chore(*): remove .travis.yml integration config file
  .travis.yml
Labels: approved, cncf-cla: yes, kind/cleanup, lgtm, size/S

#134 Fix how errors are printed
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#136 Fix Windows integration tests
  .github/workflows/test.yml
  integration_tests/klog_test.go
  klog_test.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/backlog, size/M

#140 fix serialization of special html chars
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S
