Repository kubernetes/klog, pull requests merged in 2020-05, with the labels that each got.

#143 logName(): lazily lookup userName instead of on init()
  klog_file.go
Labels: approved, cncf-cla: yes, lgtm, priority/backlog, size/M

#100 Add LogToStderr, a programatic way to log exclusively to stderr or not
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#148 Add example for co-existence of klog v1 and v2
  examples/coexist_klog_v1_and_v2/coexist_klog_v1_and_v2.go
  examples/coexist_klog_v1_and_v2/go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M

#149 Switch slack channel to #klog
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS

#150 Add apidiff script to check go signature changes
  .github/workflows/test.yml
  hack/verify-apidiff.sh
Labels: approved, cncf-cla: yes, lgtm, size/L

#152 Fix documentation for V(level)
  klog.go
Labels: approved, cncf-cla: yes, kind/documentation, lgtm, size/XS

#154 ErrorS(nil, ...) should call loggr.Error(nil, ...) instead of loggr.Info(...)
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#155 fix typo in README.md
  README.md
Labels: approved, cncf-cla: yes, lgtm, size/XS
