Repository kubernetes/klog, pull requests merged in 2020-03, with the labels that each got.

#123 klog_file: workaround stdlib.user not supporting Nano Server
  klog_file.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, priority/important-soon, size/M

#124 Backport: klog_file: workaround stdlib.user not supporting Nano Server
  klog_file.go
Labels: approved, cncf-cla: yes, kind/bug, lgtm, size/M

#128 Implement klog.KObj klog.KRef functions
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#130 upgrade go.mod dependency upgrade go 1.12 to 1.13 and add new file .gitignore
  .gitignore
  examples/go.mod
  examples/go.sum
  go.mod
Labels: approved, cncf-cla: yes, lgtm, size/M
