Repository kubernetes/klog, pull requests merged in 2021-08, with the labels that each got.

#242 Switching to logr tag v1.0.0
  go.mod
  go.sum
  klog.go
  klog_test.go
  klogr/calldepth-test/call_depth_helper_test.go
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, do-not-merge/hold, size/L

#257 export ClearLogger
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#250 Proposal serathius as approvers
  OWNERS
Labels: cncf-cla: yes, lgtm, size/XS, approved
