Repository kubernetes/klog, pull requests merged in 2021-12, with the labels that each got.

#273 structured logging: support values with line breaks
  examples/go.mod
  examples/go.sum
  examples/structured_logging/structured_logging.go
  klog.go
  klog_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#272 Fix klog lock release on panic error
  klog.go
  klog_test.go
Labels: kind/bug, size/M, cncf-cla: yes, lgtm, approved

#276 add format test for KObjs
  klog_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S, wg/structured-logging

#277 add Verbose.InfoSDepth
  klog.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#271 Using OS targeted go files to separate out the username logic.
  klog_file.go
  klog_file_others.go
  klog_file_windows.go
Labels: size/M, cncf-cla: yes, lgtm, approved

#279 Recover from nil pointers when logging
  klog.go
  klog_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S
