Repository kubernetes/klog, pull requests merged in 2021-09, with the labels that each got.

#204 fix file-based filtering symbolization
  klog.go
Labels: lifecycle/stale, cncf-cla: yes, size/XS

#260 Update to newest versions of golang 1.17.x
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#265 Fix logcheck exit function
  hack/tools/logcheck/main.go
  hack/tools/logcheck/testdata/src/allowUnstructuredLogs/allowUnstructuredLogs.go
  hack/tools/logcheck/testdata/src/doNotAllowUnstructuredLogs/doNotAllowUnstructuredLogs.go
  hack/tools/logcheck/testdata/src/k8s.io/klog/v2/klog.go
Labels: kind/bug, cncf-cla: yes, lgtm, approved, size/S
