Repository kubernetes/klog, pull requests merged in 2021-05, with the labels that each got.

#210 Call backing logr with call depth
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#237 Fix byte array display in InfoS and ErrorS
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/S

#238 Fix little nit for klog
  klog.go
  klog_test.go
  klogr/klogr.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
