Repository kubernetes/klog, pull requests merged in 2021-01, with the labels that each got.

#197 klogr output format
  klog.go
  klog_test.go
  klog_wrappers_test.go
  klogr/README.md
  klogr/klogr.go
  klogr/klogr_test.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#207 klogr call depth
  go.mod
  go.sum
  klogr/calldepth-test/call_depth_helper_test.go
  klogr/calldepth-test/call_depth_main_test.go
  klogr/klogr.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#205 test: cleanup temporary file
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, priority/backlog, size/XS, triage/accepted

#208 Fix klog missing ) in 'one_output' description
  klog.go
Labels: approved, cncf-cla: yes, lgtm, size/XS
