Repository kubernetes/klog, pull requests merged in 2021-03, with the labels that each got.

#213 Add Static linter for structured logging
  .github/workflows/test.yml
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/logcheck/README.md
  hack/tools/logcheck/main.go
  hack/tools/logcheck/main_test.go
  hack/tools/logcheck/testdata/data.go
  hack/tools/logcheck/testdata/src/k8s.io/klog/v2/klog.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#217 Fix err is nil,ErrorS should not change the log level
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#225 KObj should be able to handle nil objects
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/XS

#226 Fix cases where KMetadata interface has nil object
  klog.go
  klog_test.go
Labels: approved, cncf-cla: yes, lgtm, size/M

#229 Add check for InfoS & ErrorS parameters
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/logcheck/main.go
  hack/tools/logcheck/testdata/data.go
Labels: approved, cncf-cla: yes, lgtm, size/L

#230 logcheck: check usage of format specifier in structured log functions
  hack/tools/logcheck/main.go
  hack/tools/logcheck/testdata/data.go
Labels: approved, cncf-cla: yes, lgtm, size/M
