Repository kubernetes/klog, pull requests merged in 2022-03, with the labels that each got.

#303 structured logging: replacing Fatal/Exit/etc. without loss of flushing
  exit.go
  exit_test.go
  klog.go
  klog_test.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#296 contextual logging
  contextual.go
  contextual_test.go
  examples/output_test/output_test.go
  imports.go
  k8s_references.go
  klog.go
  klogr.go
  ktesting/example/example_test.go
  ktesting/init/init.go
  ktesting/options.go
  ktesting/setup.go
  ktesting/testinglogger.go
  ktesting/testinglogger_test.go
Labels: size/XXL, cncf-cla: yes, lgtm, approved

#304 tests: stop testing with Go 1.14
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#306 SetLoggerWithOptions: support flushing
  contextual.go
  contextual_test.go
  klog.go
Labels: size/M, cncf-cla: yes, approved

#307 StartFlushDaemon: add API with more control over flushing
  klog.go
  klog_test.go
Labels: kind/feature, size/M, cncf-cla: yes, lgtm, approved

#308 SetContextualLogger: remove unintentionally merged API call
  contextual.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#309 Cleanup OWNERS file
  OWNERS
Labels: cncf-cla: yes, lgtm, approved, size/S

#310 dependencies: avoid k8s.io/utils, fork clock code instead
  go.mod
  go.sum
  internal/clock/README.md
  internal/clock/clock.go
  internal/clock/testing/fake_clock.go
  internal/clock/testing/simple_interval_clock.go
  klog.go
  klog_test.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#311 promote contextual logging APIs to stable
  README.md
  contextual.go
  imports.go
  klogr.go
Labels: size/M, cncf-cla: yes, lgtm, approved

#313 hack/tools: drop dependency on golangci-lint
  hack/tools/go.mod
  hack/tools/go.sum
Labels: size/XXL, cncf-cla: yes, lgtm, approved

#314 StopFlushDaemon: document flushing on shutdown
  klog.go
Labels: cncf-cla: yes, lgtm, size/XS, approved

#315 logcheck: fix detection of invalid * regexp in filter
  hack/tools/logcheck/pkg/filter.go
  hack/tools/logcheck/pkg/filter_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S
