Repository kubernetes/klog, pull requests merged in 2022-06, with the labels that each got.

#329 GitHub: use apidiff with more recent Go
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#330 remove hack/tools
  .github/workflows/test.yml
  README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/logcheck/README.md
  hack/tools/logcheck/main.go
  hack/tools/logcheck/main_test.go
  hack/tools/logcheck/pkg/filter.go
  hack/tools/logcheck/pkg/filter_test.go
  hack/tools/logcheck/pkg/logcheck.go
  hack/tools/logcheck/plugin/plugin.go
  hack/tools/logcheck/testdata/src/allowUnstructuredLogs/allowUnstructuredLogs.go
  hack/tools/logcheck/testdata/src/contextual/contextual.go
  hack/tools/logcheck/testdata/src/doNotAllowUnstructuredLogs/doNotAllowUnstructuredLogs.go
  hack/tools/logcheck/testdata/src/github.com/go-logr/logr/logr.go
  hack/tools/logcheck/testdata/src/gologr/gologr.go
  hack/tools/logcheck/testdata/src/helpers/doNotAllowDirectCalls.go
  hack/tools/logcheck/testdata/src/importrename/importrename.go
  hack/tools/logcheck/testdata/src/k8s.io/klog/v2/klog.go
  hack/tools/logcheck/testdata/src/mixed/allowUnstructuredLogs.go
  hack/tools/logcheck/testdata/src/mixed/doNotAllowUnstructuredLogs.go
  hack/tools/logcheck/testdata/src/mixed/structured_logging
  hack/tools/logcheck/testdata/src/onlyAllowContextual/klog_logging
  hack/tools/logcheck/testdata/src/onlyAllowContextual/onlyAllowContextual.go
  hack/tools/logcheck/testdata/src/onlyAllowContextual/whitelistedKlog.go
  hack/tools/logcheck/testdata/src/parameters/parameters.go
  hack/tools/logcheck/testdata/src/verbose/verbose.go
Labels: size/XXL, cncf-cla: yes, lgtm, approved

#332 GIT-331: fix shadowing key from the kv pair
  internal/serialize/keyvalues.go
  internal/serialize/keyvalues_test.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#327 ktesting: capture log data in memory
  ktesting/example_test.go
  ktesting/testinglogger.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#333 GIT-275: add tests for int and struct keys
  .github/workflows/test.yml
  examples/benchmarks/benchmarks_test.go
  examples/output_test/output_test.go
  test/output.go
  test/zapr.go
Labels: cncf-cla: yes, size/L, lgtm, approved
