Repository kubernetes/klog, pull requests merged in 2022-02, with the labels that each got.

#280 Add missing Depth logging functions.
  klog.go
Labels: size/M, cncf-cla: yes, lgtm, approved

#290 log filter: ignored by V, used during log call
  klog.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#289 SetLogger/ClearLogger/SetLogFilter cleanup
  klog.go
Labels: cncf-cla: yes, lgtm, approved, size/S

#287 fixes for PR #280, refactoring, textlogger, unit test
  README.md
  internal/buffer/buffer.go
  internal/serialize/keyvalues.go
  internal/serialize/keyvalues_test.go
  internal/severity/severity.go
  internal/test/mock.go
  internal/verbosity/helper_test.go
  internal/verbosity/verbosity.go
  internal/verbosity/verbosity_test.go
  klog.go
  klog_test.go
  klogr/klogr.go
  klogr/klogr_test.go
  test/output.go
  test/output_helper.go
  test/output_test.go
  textlogger/options.go
  textlogger/textlogger.go
Labels: size/XXL, cncf-cla: yes, lgtm, approved

#295 klogr verbosity
  .github/workflows/test.yml
  examples/go.mod
  examples/go.sum
  examples/output_test/output_test.go
  klogr/klogr.go
  test/output.go
  test/output_test.go
  test/zapr.go
Labels: cncf-cla: yes, lgtm, size/XL, approved

#298 test: fix Go version matrix
  .github/workflows/test.yml
Labels: cncf-cla: yes, lgtm, size/XS, approved

#299 handle panics in MarshalLog, Error, String
  examples/go.mod
  examples/go.sum
  internal/serialize/keyvalues.go
  internal/serialize/keyvalues_test.go
  klogr/klogr.go
  test/output.go
  test/zapr.go
Labels: cncf-cla: yes, size/L, lgtm, approved

#293 Fix goroutine leak: make flushDaemon stoppable
  examples/flushing/flushing_test.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  klog.go
  klog_test.go
Labels: ok-to-test, tide/merge-method-squash, cncf-cla: yes, size/L, lgtm, approved
