Repository kubernetes/klog, pull requests merged in 2024-01, with the labels that each got.

#396 logr v1.4.1 + SetSlogLogger
  .github/workflows/test.yml
  contextual_slog.go
  contextual_slog_example_test.go
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  klogr_slog.go
  klogr_slog_test.go
  textlogger/textlogger_slog.go
Labels: cncf-cla: yes, size/L, lgtm, approved, needs-triage

#397 textlogger: allow caller to override stack unwinding
  textlogger/options.go
  textlogger/textlogger.go
  textlogger/textlogger_test.go
Labels: size/M, cncf-cla: yes, lgtm, approved, triage/accepted

#399 chore(*): fix spelling of Intel Corporation
  ktesting/contextual_test.go
  ktesting/testinglogger.go
  ktesting/testinglogger_test.go
  textlogger/textlogger.go
Labels: cncf-cla: yes, lgtm, size/XS, approved, needs-triage
